language: python
python:
  - '3.7'
  
branches:
  only:
    - master
  
cache: pip
env:
  -  LC_ALL="pt_BR.UTF-8" LC_CTYPE="pt_BR.UTF-8"
  
before_install:
  - sudo dpkg-reconfigure locales
  - openssl aes-256-cbc -K $encrypted_548a41d6cefd_key -iv $encrypted_548a41d6cefd_iv -in google-api-auth.json.enc -out google-api-auth.json -d
  
install:
  - pip install poetry
  - poetry install
  
script:
  - poetry run python calendaryo.py
