[[ slot ]]
type = "keynote"
name = "Keynote 1"
start_at = 2019-10-25 09:00:00
duration = 60
room = "keynote-room"

[[ slot ]]
type = "coffee"
name = "Café da Manhã"
start_at = 2019-10-25 10:00:00
duration = 30
room = "coffee-room"

[[ slot ]]
type = "talk"
name = "Palestra Sala 1"
start_at = 2019-10-25 10:30:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-25 10:30:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-25 10:30:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Palestra Sala 1"
start_at = 2019-10-25 11:15:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-25 11:15:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-25 11:15:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Lightning Talks"
start_at = 2019-10-25 12:00:00
duration = 30
room = "room3"

[[ slot ]]
type = "lunch"
name = "Almoço"
start_at = 2019-10-25 12:30:00
duration = 90
room = "coffee-room"