[[ slot ]]
type = "keynote"
name = "Laís Verejão (keynote)"
author = "Laís Verejão"
start_at = 2019-10-25 09:00:00
duration = 60
room = "Diamante"

[[ slot ]]
type = "keynote"
name = "Carol Willing (keynote)"
author = "Carol Willing"
start_at = 2019-10-25 17:15:00
duration = 60
room = "Diamante"

[[ slot ]]
type = "keynote"
name = "Felipe de Morais (keynote)"
author = "Felipe de Morais"
start_at = 2019-10-26 11:30:00
duration = 60
room = "Diamante"

[[ slot ]]
type = "keynote"
name = "Lorena Mesa (keynote)"
author = "Lorena Mesa"
start_at = 2019-10-26 17:15:00
duration = 60
room = "Diamante"

[[ slot ]]
type = "keynote"
name = "Débora Azevedo (keynote)"
author = "Débora Azevedo"
start_at = 2019-10-27 11:30:00
duration = 60
room = "Diamante"

[[ slot ]]
type = "keynote"
name = "Luciano Ramalho (keynote)"
author = "Luciano Ramalho"
start_at = 2019-10-27 17:15:00
duration = 60
room = "Diamante"
