[[ slot ]]
type = "talk"
name = "Assembleia APyB"
start_at = 2019-10-26 09:30:00
duration = 120
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-26 09:30:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-26 09:30:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-26 10:15:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-26 10:15:00
duration = 45
room = "room3"

[[ slot ]]
type = "lightning-talks"
name = "Lightning Talks"
start_at = 2019-10-26 11:00:00
duration = 30
room = "room3"

[[ slot ]]
type = "talk"
name = "Palestra Sala 1"
start_at = 2019-10-26 14:00:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-26 14:00:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-26 14:00:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Palestra Sala 1"
start_at = 2019-10-26 14:45:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-26 14:45:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-26 14:45:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Associação Python Brasil"
start_at = 2019-10-26 15:30:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-26 15:30:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-26 15:30:00
duration = 45
room = "room3"