[[ slot ]]
type = 'talk'
name = 'Fazendo seu chatbot do zero com Tensorflow'
author = 'Barbara Barbosa'
category = 'Data Science'
start_at = 2019-10-27 09:30:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Desvendando a caixa preta do MongoDB'
author = 'Danielle Monteiro'
category = 'Python para tudo'
start_at = 2019-10-27 10:15:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Acelerando Aplicações Científicas com Cython'
author = 'Emanuel Lima'
category = 'Data Science'
start_at = 2019-10-27 14:45:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Como montar um “App” de clima/tempo com Python e dados abertos'
author = 'Filipe Fernandes'
category = 'Data Science'
start_at = 2019-10-27 15:30:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Programando um Emulador de trás pra frente'
author = 'Henrique Bastos'
category = 'Desenvolvimento'
start_at = 2019-10-27 14:00:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'De dias para minutos, de minutos para milisegundos com SQLAlchemy'
author = 'Leonardo Rochael'
category = 'Desenvolvimento'
start_at = 2019-10-27 15:30:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Evitando algumas falhas de segurança em aplicações web com Python'
author = 'Mariana de Albuquerque'
category = 'Python para tudo'
start_at = 2019-10-27 14:00:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Python para Quants - Como Python pode ajudar na análise de investimentos'
author = 'Rafael Calixto'
category = 'Data Science'
start_at = 2019-10-27 10:15:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Continuous Documentation: se não está documentado, seu projeto não existe'
author = 'Renne Rocha'
category = 'Python para tudo'
start_at = 2019-10-27 15:30:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Microsserviços prontos para produção'
author = 'Rodrigo Mendonça'
category = 'Arquitetura'
start_at = 2019-10-27 14:45:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Como ensinar Python?'
author = 'Yan Orestes'
category = 'Pessoas'
start_at = 2019-10-27 10:15:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Título Por onde começar a estudar Ciência de Dados?'
author = 'Patricia Guisordi'
category = 'Data Science'
start_at = 2019-10-27 09:30:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Fazendo as pazes com projetos legados'
author = 'Matheus Hernandes'
category = 'Desenvolvimento'
start_at = 2019-10-27 14:00:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Tijolinho por tijolinho: Construindo APIs com Django'
author = 'Ryllari Santana'
category = 'Desenvolvimento'
start_at = 2019-10-27 09:30:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Uma abordagem de Computação Quântica usando a ferramenta Qiskit em Python'
author = 'Daniele Tavares'
category = 'Data Science'
start_at = 2019-10-27 14:00:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = '[algoritmo.info for algoritmo in algoritmos.sort()]'
author = 'Rebeca Sarai'
category = 'Desenvolvimento'
start_at = 2019-10-27 10:15:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Saúde mental e o mercado de tecnologia, vamos falar sobre?'
author = 'Leonardo Belluzzi'
category = 'Python para tudo'
start_at = 2019-10-27 14:45:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Fato ou Fake? Combatendo desinformação com Aprendizagem de Máquina e Processamento de Linguagem Natural'
author = 'Thais Almeida'
category = 'Data Science'
start_at = 2019-10-27 09:30:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Logs: A arte de fazer o software contar sua história - Estudo de caso do projeto FASTEN'
author = 'Ingrid Sena'
category = 'Desenvolvimento'
start_at = 2019-10-27 14:45:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Seis anos de PyLadies Brasil: impactos, perspectivas e desafios'
author = 'PyLadies Brasil'
category = 'Python para tudo'
start_at = 2019-10-27 15:30:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Encerramento da Python Brasil 2019'
start_at = 2019-10-27 18:15:00
duration = 45
room = 'Diamante'
