[[ slot ]]
type = 'talk'
name = 'Em nome das Boas Práticas de Código da Casa Django, Rainha do Backend, eu te sentencio a testar - A Game of Tests'
author = 'Amanda Savluchinske'
category = 'Desenvolvimento'
start_at = 2019-10-26 10:15:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Controle de Backups e rotinas com Django e Fabric'
author = 'Camilla Martins'
category = 'Arquitetura'
start_at = 2019-10-26 09:30:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'De 100 para 1000: estratégias para quem está começando a se preocupar com performance'
author = 'Filipe Ximenes'
category = 'Desenvolvimento'
start_at = 2019-10-26 10:15:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Migrações de dados sem downtimes! Truques e lições aprendidas com PostgreSQL na Olist'
author = 'Jéssica Bonson'
category = 'Arquitetura'
start_at = 2019-10-26 14:00:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'RabbitMQ, como fazer microsserviços conversarem'
author = 'João Daher'
category = 'Arquitetura'
start_at = 2019-10-26 14:45:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Liderança Técnica: Pessoas + Tecnologia'
author = 'Kátia Nakamura'
category = 'Pessoas'
start_at = 2019-10-26 14:00:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Utilizando os pandas para entender os casos de violência contra a mulher na cidade do Recife.'
author = 'Maria Fernanda'
category = 'Data Science'
start_at = 2019-10-26 14:00:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Do cartão perfurado aos supercomputadores: Fortran moderno na prática (e no Python)'
author = 'Melissa Weber'
category = 'Data Science'
start_at = 2019-10-26 14:45:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Python e Psicologia o que uma tem a oferecer a outra: a resposta para a pergunta - Por que Python atravessou a rua?'
author = 'Nelson Nolasco'
category = 'Data Science'
start_at = 2019-10-26 10:15:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Software Livre e Código Aberto - você também pode contribuir!'
author = 'Paulo Santana'
category = 'Pessoas'
start_at = 2019-10-26 15:30:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Código à prova de raios cósmicos'
author = 'Pietra Freitas'
category = 'Desenvolvimento'
start_at = 2019-10-26 15:30:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Generating Nintendo Music Over the Phone in Python with Magenta'
author = 'Sam Agnew'
category = 'Python para tudo'
start_at = 2019-10-26 15:30:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Aplicando DevOps com Automações feitas em Python e Flask'
author = 'William Oliveira'
category = 'Arquitetura'
start_at = 2019-10-26 14:45:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Python, Tipos e Segurança'
author = 'Felipe Videira'
category = 'Arquitetura'
start_at = 2019-10-26 10:15:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Empoderando mulheres na Amazônia'
author = 'PyLadies Manaus'
category = 'Pessoas'
start_at = 2019-10-26 09:30:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Cada um com seu modelo - Criando um modelo de classificação e de sugestão único por usuário'
author = 'Gabriel Bellon'
category = 'Data Science'
start_at = 2019-10-26 14:00:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Descanso: não um luxo, mas uma necessidade'
author = 'Fernando Masanori'
category = 'Pessoas'
start_at = 2019-10-26 14:45:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Escalabilidade e internacionalização com Django para milhões de acessos'
author = 'Lidiane Monteiro'
category = 'Desenvolvimento'
start_at = 2019-10-26 15:30:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Aprendizado Profundo Híbrido em Python para Análise de Sentimentos e Reconhecimento de Contexto'
author = 'Arthur Fortes'
category = 'Data Science'
start_at = 2019-10-26 09:30:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Python on Kubernetes: Garantindo escalabilidade em aplicações produtivas'
author = 'Bianca Rosa'
start_at = 2019-10-26 09:30:00
duration = 45
room = 'Onix'
