[[ slot ]]
type = 'talk'
name = 'Aprendendo e ensinando Python para “programadores alternativos”'
author = 'Alexandre Villares'
category = 'Pessoas'
start_at = 2019-10-25 10:30:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Un algoritmo de Mallado Poliedral en 3 Dimensiones para Aproximar Soluciones a Problemas Físicos Singulares'
author = 'Alexis Jawtuschenko'
category = 'Data Science'
start_at = 2019-10-25 14:45:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Tecnology is the new freedom'
author = 'Anicely Santos'
category = 'Pessoas'
start_at = 2019-10-25 11:15:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Dr. Introvertido ou: Como eu Aprendi a Parar de Me Preocupar e Amar Cultura de Time'
author = 'Betina Costa'
category = 'Pessoas'
start_at = 2019-10-25 14:00:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Black Mirror ao contrário - Uso de tecnologia (e dados) para o bem'
author = 'Bruno Evangelista'
category = 'Data Science'
start_at = 2019-10-25 14:00:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Otimizando sistemas em Python com Kibana, Elasticsearch e APM'
author = 'Bruno França'
category = 'Arquitetura'
start_at = 2019-10-25 11:15:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Python e Ciência de Dados no Combate à Corrupção'
author = 'David Cosac Junior e Cláudio Augusto Soares'
category = 'Data Science'
start_at = 2019-10-25 10:30:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Música com Python e FoxDot'
author = 'Diego Guimarães'
category = 'Python para tudo'
start_at = 2019-10-25 15:30:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Código legado de machine learning? Como migramos para Python 3 sem sofrimento'
author = 'Eder Martins'
category = 'Desenvolvimento'
start_at = 2019-10-25 15:30:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = '1 + 1 = 1 ou Pareamento de Registros com Python'
author = 'Flávio Juvenal'
category = 'Data Science'
start_at = 2019-10-25 14:00:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'A anatomia do code review'
author = 'Guilherme Garnier'
category = 'Pessoas'
start_at = 2019-10-25 11:15:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Docker: melhorando sua vida como desenvolvedor Python'
author = 'Gustavo Carvalho'
category = 'Arquitetura'
start_at = 2019-10-25 14:00:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Controlando um braço robótico com MicroPython'
author = 'Juliana Karoline'
category = 'Python para tudo'
start_at = 2019-10-25 15:30:00
duration = 45
room = 'Diamante'

[[ slot ]]
type = 'talk'
name = 'Construindo plugins para o Pytest'
author = 'Rafael Henrique'
category = 'Desenvolvimento'
start_at = 2019-10-25 10:30:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = '1 ano após primeira Python Brasil'
author = 'Tyrone Damasceno'
category = 'Pessoas'
start_at = 2019-10-25 14:45:00
duration = 45
room = 'Onix'

[[ slot ]]
type = 'talk'
name = 'Desenhando com Python dentro do Navegador'
author = 'Bernardo Fontes'
category = 'Desenvolvimento'
start_at = 2019-10-25 14:45:00
duration = 45
room = 'Esmeralda'

[[ slot ]]
type = 'talk'
name = 'Serveless: zero to hero'
author = 'Giana de Almeida'
category = 'Arquitetura'
start_at = 2019-10-25 14:45:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Ciência de Dados no cotidiano: o que os dados dizem sobre o real comportamento da população?'
author = 'Juliany Raiol'
category = 'Data Science'
start_at = 2019-10-25 11:15:00
duration = 45
room = 'Topázio'

[[ slot ]]
type = 'talk'
name = 'Como um grupo de estudos estimula a troca de saber dentro da comunidade PyLadies São Paulo'
author = 'Grupo de Estudos em Data Science'
category = 'Pessoas'
start_at = 2019-10-25 10:30:00
duration = 45
room = 'Onix'
