[[ slot ]]
type = "talk"
name = "Palestra Sala 1"
start_at = 2019-10-25 10:30:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-25 10:30:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-25 10:30:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Palestra Sala 1"
start_at = 2019-10-25 11:15:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-25 11:15:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-25 11:15:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Lightning Talks"
start_at = 2019-10-25 12:00:00
duration = 30
room = "room3"

[[ slot ]]
type = "talk"
name = "Palestra Sala 1"
start_at = 2019-10-25 14:00:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-25 14:00:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-25 14:00:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Palestra Sala 1"
start_at = 2019-10-25 14:45:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-25 14:45:00
duration = 45
room = "room2"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-25 14:45:00
duration = 45
room = "room3"

[[ slot ]]
type = "talk"
name = "Associação Python Brasil"
start_at = 2019-10-25 15:30:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 2"
start_at = 2019-10-25 15:30:00
duration = 45
room = "room1"

[[ slot ]]
type = "talk"
name = "Palestra Sala 3"
start_at = 2019-10-25 15:30:00
duration = 45
room = "room3"