[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "LuizaLabs"
start_at = 2021-10-11T10:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Jusbrasil"
start_at = 2021-10-11T11:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Carta"
start_at = 2021-10-11T13:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Buser"
start_at = 2021-10-11T14:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Ebury"
start_at = 2021-10-11T16:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "MELI"
start_at = 2021-10-11T17:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "MELI"
start_at = 2021-10-12T10:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "LuizaLabs"
start_at = 2021-10-12T11:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Jusbrasil"
start_at = 2021-10-12T13:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Carta"
start_at = 2021-10-12T14:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Buser"
start_at = 2021-10-12T16:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Ebury"
start_at = 2021-10-12T17:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Ebury"
start_at = 2021-10-13T10:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "MELI"
start_at = 2021-10-13T11:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "LuizaLabs"
start_at = 2021-10-13T13:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Jusbrasil"
start_at = 2021-10-13T14:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Carta"
start_at = 2021-10-13T16:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Buser"
start_at = 2021-10-13T17:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Buser"
start_at = 2021-10-14T10:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Ebury"
start_at = 2021-10-14T11:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "MELI"
start_at = 2021-10-14T13:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "LuizaLabs"
start_at = 2021-10-14T14:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Jusbrasil"
start_at = 2021-10-14T16:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Carta"
start_at = 2021-10-14T17:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Carta"
start_at = 2021-10-15T10:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Buser"
start_at = 2021-10-15T11:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Ebury"
start_at = 2021-10-15T13:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "MELI"
start_at = 2021-10-15T14:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "LuizaLabs"
start_at = 2021-10-15T16:00:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"

[[slot]]
type = "jobfair"
author = ""
description = "Feira de empregos"
name = "Jusbrasil"
start_at = 2021-10-15T17:30:00-03:00
duration = 90
room = ""
youtube_channel = "https://discord.gg/AGe29Rsh"
