[[slot]]
type = "light"
author = ""
description = "Palestras Relâmpagos"
name = "Você !!"
start_at = 2021-10-11T19:50:00-03:00
duration = 50
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/5XN1r7Sf6wM"

[[slot]]
type = "light"
author = ""
description = "Palestras Relâmpagos"
name = "Você !!"
start_at = 2021-10-12T19:50:00-03:00
duration = 40
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/ia-W6GwDTto"

[[slot]]
type = "light"
author = ""
description = "Palestras Relâmpagos"
name = "Você !!"
start_at = 2021-10-13T20:20:00-03:00
duration = 40
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/-OMV8DEEN8E"

[[slot]]ß
type = "light"
author = ""
description = "Palestras Relâmpagos"
name = "Você !!"
start_at = 2021-10-14T19:50:00-03:00
duration = 40
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/Ul8aA8w7DTw"
