[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Melissa Weber Mendonça"
start_at = 2020-11-02T20:00:00
duration = 90

[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Diana Rodriguez"
start_at = 2020-11-03T20:00:00
duration = 90

[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Thais Viana"
start_at = 2020-11-04T20:00:00
duration = 90

[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Álvaro Justen (Turicas)"
start_at = 2020-11-05T20:00:00
duration = 90

[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Ana Paula Gomes"
start_at = 2020-11-06T18:30:00
duration = 90
