[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Melissa Weber Mendonça"
start_at = 2020-11-02T20:00:00
duration = 90
youtube_channel = "https://www.youtube.com/watch?v=2vTDUZxSHvo"
discord_channel = "https://discord.com/channels/767870635874582600/772949769857269831"

[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Diana Rodriguez"
start_at = 2020-11-03T20:00:00
duration = 90
youtube_channel = "https://www.youtube.com/watch?v=2DhFUMwAGyI"
discord_channel = "https://discord.com/channels/767870635874582600/772949769857269831"
slides_url = "http://turicas.info/slides/sobre-os-ombros-de-gigantes/pybr2020.html"

[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Thais Viana"
start_at = 2020-11-04T20:00:00
duration = 90
youtube_channel = "https://www.youtube.com/watch?v=ufYGPyanDoA"
discord_channel = "https://discord.com/channels/767870635874582600/772949769857269831"

[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Álvaro Justen (Turicas)"
start_at = 2020-11-05T20:00:00
duration = 90
youtube_channel = "https://www.youtube.com/watch?v=cUYFIga_JXU"
discord_channel = "https://discord.com/channels/767870635874582600/772949769857269831"

[[ slot ]]
type = "keynote"
name = "Keynote"
author = "Ana Paula Gomes"
start_at = 2020-11-06T18:30:00
duration = 90
youtube_channel = "https://www.youtube.com/watch?v=FRFLYQejHFE"
discord_channel = "https://discord.com/channels/767870635874582600/772949769857269831"
