[[ slot ]]
type = "mesa-redonda"
name = "Mesa Redonda - PyLadies"
description = "Mesa redonda das PyLagies"
start_at = 2020-11-02T10:00:00
duration = 120

[[ slot ]]
type = "mesa-redonda"
name = "Os desafios da transformação digital nos municípios brasileiros"
description = "A mesa redonda discutirá, entre outros pontos, as dificuldades, financeiras e de capacitação técnica, enfrentadas pelos municípios brasileiros, para prover serviços que possam facilitar a participação do cidadão na vida política brasileira e para atender as exigências de transparência da sociedade. Do outro lado as iniciativas que visam facilitar o provimento de serviços e soluções utilizando tecnologias baseadas em código aberto e comunidades técnicas, e a importância de se fomentar esse tipo de iniciativa no Brasil."
start_at = 2020-11-03T10:00:00
duration = 120
