[[ slot ]]
type = "abertura"
name = "Abertura Oficial da Python Brasil 2020"
description = ""
start_at = 2020-11-02T09:30:00
duration = 30
youtube_channel = "https://www.youtube.com/watch?v=-DFgRTGRCA8&t=537"

[[ slot ]]
type = "mesa-redonda"
name = "PyLadies pelo Brasil: construção coletiva, diversidade e inclusão"
description = ""
start_at = 2020-11-02T10:00:00
duration = 120
youtube_channel = "https://www.youtube.com/watch?v=-DFgRTGRCA8&t=2305"
discord_channel = "https://discord.com/channels/767870635874582600/772807508963753994"

[[ slot ]]
type = "mesa-redonda"
name = "Os desafios da transformação digital nos municípios brasileiros"
description = "A mesa redonda discutirá, entre outros pontos, as dificuldades, financeiras e de capacitação técnica, enfrentadas pelos municípios brasileiros, para prover serviços que possam facilitar a participação do cidadão na vida política brasileira e para atender as exigências de transparência da sociedade. Do outro lado as iniciativas que visam facilitar o provimento de serviços e soluções utilizando tecnologias baseadas em código aberto e comunidades técnicas, e a importância de se fomentar esse tipo de iniciativa no Brasil."
start_at = 2020-11-03T10:00:00
duration = 120
author = "Mario Sérgio, Maria Vitória Ramos, Luis Kimaid, Márcio Coimbra"
youtube_channel = "https://www.youtube.com/watch?v=a1LHfsYq8rU"
discord_channel = "https://discord.com/channels/767870635874582600/772807508963753994"

[[ slot ]]
type = "mesa-redonda"
name = "Pizza de Dados Ao Vivo: Divulgação Científica"
description = "Nessa atividade vocês vão poder acompanhar a gravação de um episódio do Podcast Pizza de Dados e vai ter a oportunidade de mandar sua pergunta ao vivo para todas as participantes! O Pizza é o primeiro e mais querido podcast brasileiro sobre ciência de dados. Fundado em 2017, o podcast mensalmente conversa pessoas especialistas na área de dados e leva ao público de forma leve e divertida conhecimento sobre as mais diversas subáreas dentro da ciência de dados. Nesta edição especial ao vivo, vamos ter a participação de Carla Vieira do canal E A.I Carla, Mila Laranjeira e Vivi Mota do canal Peixe Babel e iremos discutir sobre a divulgação científica e ciência de dados no Brasil! Não deixe de assistir esse episódio inédito pela primeira vez ao vivo. Essa atividade é voltada para o públicos de todos os níveis e não precisa ter conhecimento prévio do tema."
start_at = 2020-11-04T10:30:00
duration = 120
author = "Letícia Portella, Jessica Temporal, Carla Vieira, Mila Laranjeira e Vivi Mota"
youtube_channel = "https://www.youtube.com/watch?v=ruaGqonhT7w"
discord_channel = "https://discord.com/channels/767870635874582600/772807508963753994"

[[ slot ]]
type = "mesa-redonda"
name = "Associação Python Brasil (APyB)"
description = "Neste espaço, a Associação Python Brasil (APyB) terá uma conversa aberta com pessoas que contribuiram com a história da APyB, e apresentará o papel da Associação como suporte à comunidade Python brasileira. As pessoas convidadas para esta mesa redonda são: Tania Almeida, Luciano Ramalho, Erico Andrei, Osvaldo Santana, Leo Rochael"
start_at = 2020-11-05T10:00:00
duration = 120
author = "Patrick Mazulo e Gustavo Carvalho"
discord_channel = "https://discord.com/channels/767870635874582600/772807508963753994"
youtube_channel = "https://www.youtube.com/watch?v=2ChVEdZ_NhI"

[[ slot ]]
type = "mesa-redonda"
name = "Transmissão de conhecimento dentro da comunidade"
description = ""
author = "Patrícia Morimoto, Eduardo Mendes, Fabrícia Diniz e Fernando Masanori"
start_at = 2020-11-06T10:00:00
duration = 120
discord_channel = "https://discord.com/channels/767870635874582600/772807508963753994"
